name: Delete Environment on Branch Deletion

on:
  delete:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_REGION: europe-west4
  GKE_ZONE: europe-west4-a

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Sanitize Branch Name
        id: branch_sanitizer
        run: |
          RAW_BRANCH="${{ github.event.ref }}"
          SANITIZED=$(echo "$RAW_BRANCH" | sed 's|refs/heads/||' | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9-]+/-/g' | sed -E 's/^-+|-+$//g' | cut -c1-63)
          if [[ ! "$SANITIZED" =~ ^[a-z0-9] ]]; then
            SANITIZED="ns-$SANITIZED"
          fi
          if [[ "$SANITIZED" == "main" ]]; then
            SANITIZED="project"
          fi
          echo "namespace=$SANITIZED" >> $GITHUB_OUTPUT

      - uses: google-github-actions/auth@v3
        with:
          credentials_json: "${{ secrets.GKE_SA_KEY }}"

      - name: "Set up Cloud SDK"
        uses: google-github-actions/setup-gcloud@v3

      - name: "Get GKE credentials"
        uses: "google-github-actions/get-gke-credentials@v2"
        with:
          cluster_name: "${{ env.GKE_CLUSTER }}"
          project_id: "${{ env.PROJECT_ID }}"
          location: "${{ env.GKE_ZONE }}"

      - name: Delete Kubernetes Namespace
        run: |
          kubectl delete namespace ${{ steps.branch_sanitizer.outputs.namespace }} --ignore-not-found